### ISSUE TITLE
Refactor: try aligned string for simd in lexer

### ISSUE THREAD

**Issue by Boshen** [Boshen/oxc#43]
https://github.com/Boshen/oxc/pull/26#discussion_r1116408111

> You can guarantee that remainder is always empty or unimportant (thus you don't need to check for it) if you add enough zeros at the end of bytes. I do this in quick-lint-js when I load the file from the filesystem, so everything can safely assume that the extra bytes are present. (I have a dedicated type for this called padded_string_view which doesn't allow breaking this invariant.)

**Comment by YoniFeng** [comment]
Interesting.
This is ~purely for ergonomics, right?
i.e. I'd expect perf gains to be non-existent or negligible, even if implemented in as close to a "zero-cost abstraction" as possible (but of course, only measuring will tell).

As @stager mentioned, this has to be done on the filesystem boundary/right when loading the file's contents.
That way only a single reallocation+copy is needed. (I wonder if there's a way to avoid even that, since file contents can be large. I'm guessing using `fs::metadata.len()` isn't worth it though).

Do you have any thoughts on where this shared "padded_string" should be located, filesystem structure-wise?
Anything accessing the Parser will need to have access to it as well.
Should it be in a new crate?

**Comment by Boshen** [comment]
By looking at the PR, I think this over complicated things without significant performance increase.
 
If we are ever going to release oxc as crates, exposing this `PaddedStringView` is not really user friendly. 

So I suggest we close this issue and the PR. I'm glad you tried you this. Perhaps you can pop into our Discord channel for quicker feedback, you'll be able see whether I'm online or not.

**Comment by YoniFeng** [comment]
If there's potential for future SIMD optimizations, I think it could be ~handy overall.

The external API can always have an overload that takes a `&str`, it just means that using it will mean allocation+copy.
I'll try to work on it a little more, and if you still don't like it we can throw it away?

**Comment by Boshen** [comment]
I'm not seeing any perf improvements and I don't want to waste your time on this for such small gain. 

A more interesting task would be the allocator one.

**Comment by YoniFeng** [comment]
@Boshen can close this issue
